### ISSUE TITLE
Allow elasticsearch.host property to be an array

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#131]
Primarily for readability, but it also would be easier for other deployment manifest tools which can embed existing data.

Confusing...

```
properties: 
  elasticsearch:
    host: "0.api.silo-private.sanity-test.bosh,0.elasticsearch.silo-private.sanity-test.bosh,1.elasticsearch.silo-private.sanity-test.bosh"
```

Better...

```
properties: 
  elasticsearch:
    host:
      - 0.api.silo-private.sanity-test.bosh
      - 0.elasticsearch.silo-private.sanity-test.bosh
      - 1.elasticsearch.silo-private.sanity-test.bosh
```

This was originally a string from when logstash needed to talk directly to a single host rather than to a local elasticsearch process.
