### ISSUE TITLE
How we should handle ES plugin?

### ISSUE THREAD

**Issue by bonzofenix** [logsearch/logsearch-boshrelease#139]
Hi David,
So I been working on getting 2 plugins on ES for our Logsearch deployment:
https://github.com/royrusso/elasticsearch-HQ
https://github.com/lmenezes/elasticsearch-kopf

I got this working by adding 1 package to the release which is called es-plugins
This way I can specified in my properties:

```
...
properties:
    elasticsearch:
    - hq: file:///var/vcap/packages/es-plugins/elasticsearch-hq.zip
    - kopf: file:///var/vcap/packages/es-plugins/elasticsearch-kopf.zip
```

Do you think this worth being merged to the main trunk? 
If thats the case we would need to upload those blobs to the public buckets of yours.

**Pros:**
- Do not need internet connection to use this 2 particular plugins. 
- User can add plugins on src at: src/es-plugins/elasticsearch-PLUGIN_NAME.zip

**Cons:**
- Requires to create a new release whenever you add packages.
  
  What do you think? is this the right approach?

Thanks!
