### ISSUE TITLE
Error 40001: Required property `name' was not specified in object ({})

### ISSUE THREAD

**Issue by acrlewis** [logsearch/logsearch-boshrelease#153]
I tested this with spiff version 1.0.6 and 1.0.7

```
./generate_deployment_manifest aws templates/stub.aws.yml > logsearch.yml
```

From the logsearch.yml manifest generated, the api job has the following:

```
jobs:
- instances: 1
  name: api
.....
.....
release: logsearch
  resource_pool: logsearch_api
  templates:
  - {}
  - name: elasticsearch
  - name: api
  - name: kibana
```

This results in Error 40001: Required property `name' was not specified in object ({}) when trying to deploy.
