### ISSUE TITLE
Allow disabling default elasticsearch output for parser job

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#191]
For those cases where you want to specify all your own outputs via `logstash_filter.outputs`

**Comment by simonjohansson** [comment]
Will this also include to split out elasaticsearch itself from the parser job and reuse the elasticsearch job that is already in the release?

Would be great if in the manifest we could say

```
- name: parser
  templates:
  - name: elasticsearch
  - name: parser
....
```

so we get more flexibility.

As in our case we would not want to run ES directly on the parsers.
