### ISSUE TITLE
YAML error while generating deployment manifest

### ISSUE THREAD

**Issue by olzorenko** [logsearch/logsearch-boshrelease#225]
Hello All!

I've faced an issue while deploying logsearch-boshrelease to vsphere IaaS. I've tried to google it but with no lack.

Here are my steps.
1. I've uploaded release by using following command:

`bosh upload release https://bosh.io/d/github.com/logsearch/logsearch-boshrelease`

I see it in bosh releases output:

```
mac:logsearch-boshrelease oleksii$ bosh releases

Acting as user 'admin' on 'bosh'

+-----------+------------+-------------+
| Name      | Versions   | Commit Hash |
+-----------+------------+-------------+
| cf        | 225        | 24c131a5+   |
|           | 225+dev.2  | 545c1f95+   |
|           | 225+dev.3  | 545c1f95+   |
|           | 225+dev.5  | 545c1f95+   |
|           | 225+dev.6  | 545c1f95+   |
|           | 225+dev.7  | 545c1f95+   |
|           | 225+dev.8  | 545c1f95+   |
|           | 225+dev.9  | 545c1f95+   |
|           | 225+dev.10 | 545c1f95+   |
|           | 225+dev.11 | 545c1f95+   |
|           | 233        | 11e3eaec+   |
|           | 234*       | 650248ea+   |
| cf-redis  | 424*       | 5070e429    |
| logsearch | 201.0.16   | 517e9e83+   |
+-----------+------------+-------------+
(*) Currently deployed
(+) Uncommitted changes
```
1. Then I've cloned a repo:

`git clone https://github.com/logsearch/logsearch-boshrelease.git`
1. The problem appears when I try to generate a deployment manifest. Here is my stub file logsearch-stub.yml:

```

---
meta:

releases:
- name: logsearch
  version: latest

name: logsearch-test
director_uuid: 810035e6-64ba-49e4-98ec-1485781bfc79


networks:
- name: default 
  subnets:
  - range: 172.30.113.0/24
    gateway: 172.30.113.254
    dns:
    - 10.143.96.30
    reserved:
    - 172.30.113.224
    static:
    - 72.30.113.20 - 72.30.113.30
    cloud_properties:
      name: sub-cf-az1
```

And when I'm running:

`mac:logsearch-boshrelease oleksii$ ./scripts/generate_deployment_manifest vsphere logsearch-stub.yml > logsearch.yml`

I'm receiving an error:

`./scripts/../templates/logsearch-infrastructure-vsphere.yml: unmarshal []byte to yaml failed: yaml: map merge requires map or sequence of maps as the value`

I've not edited any other file except my mentioned below stub.

P.S. Actually I've wanted to deploy https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry
but as I seen in docs: 

> Deploying
> 
> This documentation assumes that you have a working LogSearch deployment and that bosh_cli is pointed at the right director.
> 1. Fetch your running LogSearch BOSH deployment manifest
> 
> $ bosh download manifest $logsearch_deployment_name > ~/workspace/logsearch.yml

So I thought I need to deploy logsearch-boshrelease first.

Please kindly advise what should I do with this error.

Best Regards,
Oleksii.
