### ISSUE TITLE
Wich pattern i need to use on kibana settings?

### ISSUE THREAD

**Issue by vfonsecapv** [logsearch/logsearch-boshrelease#227]
Thanks for any help!

**Comment by cromega** [comment]
@vfonsecapv: `logstash-*` unless you configured something custom.

https://github.com/logsearch/logsearch-boshrelease/blob/develop/jobs/parser/spec#L56

**Comment by cromega** [comment]
@vfonsecapv: does this answer your question?

**Comment by vfonsecapv** [comment]
I figured that after the deployment he would already have the logs of the machines managed by bosh. I need to perform a new deployment of Cloud Foundry and Diego, pointing to the parser?

Is there any material that can explain how to do this? I used / logsearch-for-CloudFoundry, but it has many problems and I want to try it without him.

I appreciate the help!

**Comment by kirederik** [comment]
@vfonsecapv

You need to configure your CF deployment to forward logs to the ingestor. You have to set the `syslog_daemon_config` property in your CF deployment manifest:

```
properties:
  syslog_daemon_config:
    address: <ingestor ip>
    port: <ingestor port>
    transport: <syslog protocol>
```

and redeploy CF

Does this solve your question/the issue?
