### ISSUE TITLE
Ingest BOSH NATs messages for all BOSH deployed VMs

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#233]
Lets add a ingestor-bosh-nats job to the default templates to grab all the BOSH healthcheck message from BOSH deployed VMs.

We can do this in a similar way to how we grab just the logseach BOSH healthcheck messages in the cluster_monitor VM, ie:

```
- name: ingestor-bosh-nats
  templates:
  - name: ingestor_syslog
    release: logsearch
  - name: nats_to_syslog
    release: logsearch
  ... snip ...
  properties:
    logstash_ingestor:
      syslog:
        port: 514
    redis:
      host: 10.0.16.52
      congestion_interval: 10
      congestion_threshold: 1000000
    nats_to_syslog:
      nats:
        user: nats
        password: bd233d81XXXXXX
        machines:
        - 10.0.16.5
      syslog:
        host: 127.0.0.1
        port: 514
```
