### ISSUE TITLE
Template setting to control shard count

### ISSUE THREAD

**Issue by t2sa** [logsearch/logsearch-boshrelease#234]
Request for template setting to control shard count. Thx.

**Comment by kirederik** [comment]
Hi @t2sa 

To change the default number of shards (5) and replicas (1), update the maintenance job in your stub with:

``` yaml
- name: maintenance
  instances: 1
  properties:
    elasticsearch_config:
      templates:
      - shards-and-replicas: "{ \"template\" : \"*\", \"order\" : 99, \"settings\" : { \"number_of_shards\" : NUMBER_OF_SHARDS, \"number_of_replicas\" : NUMBER_OF_REPLICAS } }"
```

Thanks!
