### ISSUE TITLE
Zero downtime ES deployments

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#51]
@dpb587 asks

> How can we adjust our bosh deployments to upgrade/restart elasticsearch nodes one at a time (serial = true), but then wait for green cluster before continuing with the next node?

**Comment by mrdavidlaing** [comment]
@wdneto - do you have any ideas here?

**Comment by aristotelesneto** [comment]
This can be accomplished by combining a couple of things together.

1) Override the global "update:" on the job you only want 1 node to be restarted at a time on the deployment manifest, and set "max_in_flight: 1". This ensures only one node is ever worked on at a time.

2) Setup a drain script for the job.  The way drain scripts work, is that before bosh sends a shutdown command it runs the drain script, meaning that it won't prevent BOSH from continuing to the next node per se, but instead it will prevent the next node from going down before knowing the cluster is ok (ie. the script runs on the next node, not on the node you just upgraded).

Simply doing option 2 should suffice, but I think it's probably best to do both.

The drain script isn't really documented, but [here is where BOSH handles it](https://github.com/cloudfoundry/bosh/blob/master/bosh_agent/lib/bosh_agent/message/drain.rb). 
A couple of major quirks:
- The sample script has to be named "bin/drain" (destination file on the job spec)
- If you're collocating multiple jobs together, the drain script will only run for the first job specified in the manifest (bug, reported but not yet fixed) 
- The drain script expects only an integer as output (on stdout, any other text will cause it to error), as well as an exit code of 0. 
  - Exiting with anything other than 0 means you will need to ssh into the machine to fix the reason why (ie. theres no command you can send to bosh from the outside to tell it to ignore the exit code of the drain script).
  - If the output of the script is a negative integer (eg: -N) , bosh wait N seconds before sending another drain command, however, when it does the arguments of the script changes, which I found very annoying.

Here is [a basic sample](https://gist.github.com/wdneto/b6f64c805652ddfb60ca) I used for removing an OSD from a Ceph cluster when a node is deleted.

The useful available options are job_shutdown (when the node is being deleted, useful for removing itself from a cluster, triggering permanent evacuation) and job_changed (job is being updated, but should still remain in the cluster).

**Comment by aristotelesneto** [comment]
[Here is another sample drain script](https://github.com/cloudfoundry/cf-release/blob/master/jobs/dea_next/templates/deterministic_drain.rb), from the DEA.

**Comment by mrdavidlaing** [comment]
@wdneto - Thanks - these features open up lots of possibilities.

A question:

Consider a deployment spread over multiple AZs, with 1 ES job (with 2 instances) / AZ

```
jobs:
- name: elasticsearch_z1
  instances: 2
  update:
    serial: true
    max_in_flight: 1
...
- name: elasticsearch_z2
  instances: 2
  update:
    serial: true
    max_in_flight: 1
```

Will this update in the following serial order? `elasticsearch_z1/0` => `elasticsearch_z1/1` => `elasticsearch_z2/0` => `elasticsearch_z2/1` ?

**Comment by dpb587** [comment]
@wdneto, I agree it's a very helpful solution - thanks!

@mrdavidlaing, in your example, I was assuming that `serial`/`max_in_flight` was job-specific, so `z1/0` and `z2/0` would both go offline for updates concurrently. It seems like BOSH would require a separate `update.group` sort of setting in order to correlate multiple jobs together into a single update workflow.

**Comment by aristotelesneto** [comment]
@dpb587 it's better to think about the serial option in the global context, as opposed to job specific. The equivalent of 'serial' for a job specific is essentially max_in_flight: 1 and canaries: 1.

If your default option is serial: false, and you have a manifest like so:

```
jobs:
- name: job1
- name: job2
- name: job3
...
- name: elasticsearch_z1
  update:
    serial: true
    max_in_flight: 1
...
- name: job4
- name: job5
- name: elasticsearch_z2
  instances: 2
  update:
    serial: true
    max_in_flight: 1
```

BOSH will start job1/0, job2/0, job3/0 in parallel, each with their respective (or the global) canaries/max_in_flight options.

Then it spins up elasticsearch_z1/0 by itself (provided canaries:1), then z1/1.

Then it will spin up job4/0, job5/0 in parallel.

And finally, elasticsearch_z2/0, then z2/1.

So the progression for the example @mrdavidlaing mentioned would be z1/0, z1/1, then proceed to z2/0 and z2/1.

**Comment by dpb587** [comment]
Oh, interesting; thanks for explaining that.

**Comment by mrdavidlaing** [comment]
To talk specifics; I propose we change our biggest logsearch cluster's jobs look like this:

```
update:
  serial: true          # default to serial updates to keep overall cluster online
  max_in_flight: 1  # only update 1 instance in a job group at a time

jobs:
- name: ingestor
  instances: 1
  update:
    serial: false
- name: queue
  instances: 1
  update:
    serial: false

- name: api
  instances: 1

- name: log_parser-1a
  instances: 1
  update:
    serial: false
- name: log_parser-1b
  instances: 1
  update:
    serial: false
- name: log_parser-1c
  instances: 1
  update:
    serial: false

- name: elasticsearch_eu-west-1a
  instances: 2
- name: elasticsearch_eu-west-1b
  instances: 2
- name: elasticsearch_eu-west-1c
  instances: 2
```

Which should lead to a deployment pattern of:
- ingestor, queue
- api
- log_parser-1a/b/c
- elasticsearch_eu-west-1a/0
- elasticsearch_eu-west-1a/1
- elasticsearch_eu-west-1b/0
- elasticsearch_eu-west-1b/1
- elasticsearch_eu-west-1c/0
- elasticsearch_eu-west-1c/1

Have I interpreted how this works correctly?
Is this the deploy behaviour we want?

**Comment by aristotelesneto** [comment]
Hrmm, cant say I tried the anti-pattern :-)

That would be mostly equivalent to:

```
update:
  serial: false
  max_in_flight: 1  # only update 1 instance in a job group at a time

jobs:
- name: ingestor
  instances: 1
- name: queue
  instances: 1

- name: api
  instances: 1
  update:
    serial: true

- name: log_parser-1a
  instances: 1
- name: log_parser-1b
  instances: 1
- name: log_parser-1c
  instances: 1

- name: elasticsearch_eu-west-1a
  instances: 2
- name: elasticsearch_eu-west-1b
  instances: 2
  update:
    serial: true
- name: elasticsearch_eu-west-1c
  instances: 2
```

The pattern would then be:
- ingestor, queue
- api
- log_parser-1a/b/c, elasticsearch_eu-west-1a/0
  - elasticsearch_eu-west-1a/1
- elasticsearch_eu-west-1b/0
  - elasticsearch_eu-west-1b/1
- elasticsearch_eu-west-1c/0
  - elasticsearch_eu-west-1c/1
