### ISSUE TITLE
Reconsider how we do logstash filters

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#58]
I think our current approach to logstash filter configuration is too fragile. I think `logsearch-boshrelease` should manage the architecture and define the conventions, but have minimal impact on its usage. While the set of filters in `logsearch-filters-common` is convenient to have pre-installed, it becomes very inconvenient to end deployments because it significantly affects how users' events are parsed and affects dashboards that we don't already manage and provide an upgrade path for.

For example, we updated `json` in common, but we also had a `json` internally with our own timezone configuration and another patch. If we deployed release 15 because we wanted the upgraded dependencies, we would be breaking how all our events are parsed because the common `json` filter was configured with a higher precedence than our internal one. Even knowing that difference, we're still hard pressed for getting an integration test suite going and being confident in the upgrade.

I propose...
1. We no longer embed `logsearch-filters-common` in our `log_parser`. We can default a published `logsearch-filters-common` artifact as the default `logstash_parser.filters` in the `spec`, but we don't forcefully embed the filters.
2. We refactor the logstash config-generating script out of `log_parser_ctl` and into a separate script which accepts arbitrary arguments of filters to use (e.g. `*.tar`, `*.tar.gz`, `*.zip`, `file://*`) and outputs to `STDOUT` the usable logstash `filters { ... }` section.
3. We add an "integration test" type command to `logsearch-filters-common` which reuses that refactored script, allowing end users to write integration tests against a known set of filters.
4. We require users to include the `logsearch-filters-common` artifact alongside their own artifacts in their deployment manifest, if they want to continue using it.

Which means, most notably, that users can upgrade the architecture and the already user-customizable parser side of things independently and safely.

**Comment by dpb587** [comment]
@mrdavidlaing, @wdneto thoughts?

**Comment by mrdavidlaing** [comment]
`logsearch-filters-common` currently contains the following:

**Transport**:
1. 10-syslog_standard.conf
2. 20-nxlog_standard.conf
**Data**:
3. 30-json.conf
4. 75-elasticsearch_request.conf
5. 75-nginx_combined.conf

I think we should remove all but the Transport filters from  `logsearch-filters-common` and then externalised as suggested.

**Comment by dpb587** [comment]
I find it difficult to draw the line between transport and message format. For example, nxlog could use the syslog protocol to ship syslog messages (i.e. double encoded), but after nxlog, there's not a syslog parser.

What if we changed things up and made this more a repository of easy to use snippets that can be included by other repos. So, get rid of the numbered prefixes here, then in our internal filter configuration, if we want syslog to be at 10, we symlink `10-syslog_standard.conf` to `../vendor/logsearch-filters-common/src/syslog_standard.conf`.

**Comment by dpb587** [comment]
We'd still use the repo to define a default set of filters, but it'll simply be a `default` directory which prioritizes and symlinks to the files like normal user repos will want to do.

**Comment by mrdavidlaing** [comment]
What do you think about enabling the selection / ordering of filters to be specified in the deployment manifest?

Eg:

```
  logstash_parser:
    filters:
    - url: "https://ci-logsearch.s3.amazonaws.com/logsearch-filters-common/logsearch-filters-common-1.5-ef354.tgz"
      selected: 
      - {syslog,nxlog}_standard.conf
      - elasticsearch_request.conf
      - nginx_combined.conf
    - url: "https://ci-logsearch.s3.amazonaws.com/logsearch-filters-internal/logsearch-filters-internal-1.8-ff324.tgz"
      selected: 
      - *
```

In this was you can "see" what filters are going to be run, and in what order; and you have quite a bit of flexibility to include and order the filters you are using

We could also default to:

```
  logstash_parser:
    filters:
    - url: "https://ci-logsearch.s3.amazonaws.com/logsearch-filters-common/logsearch-filters-common-1.5-ef354.tgz"
      selected: 
      - *
```

Which would replicate our current behaviour
