### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#74]
Evaluate merging the multi-tenant functionality from @malston's [multi-tenant fork](https://github.com/pivotalservices/logsearch-boshrelease/tree/multi-tenant) back into master

**Comment by mrdavidlaing** [comment]
Multi-tenancy can be implemented in (at least) 2 ways in ElasticSearch
1. Index(s) / tenant - eg, `{TENANT_ID}-{YYYY.MM.DD}`
2. Extra `tenant_id` field with forced filter

What are the pros and cons of each strategy?

**Comment by mrdavidlaing** [comment]
(2) above could be implemented using ES's [Index Aliases](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-aliases.html), such that all queries to the alias resolve to queries to an index with an additional filter, eg:

Create alias:

```
curl -XPOST 'http://localhost:9200/_aliases' -d '{
    "actions" : [
        {
            "add" : {
                 "index" : "logstash-2014-09-14",
                 "alias" : "5242-TENANTID-ef615-logstash-2014-09-14",
                 "filter" : { "term" : { "tenant_id" : "5242-TENANTID-ef615" } }
            }
        }
    ]
}'
```

Use alias:

```
curl -XGET 'http://localhost:9200/5242-TENANTID-ef615-logstash-2014-09-14/_search
```

automatically adds `"filter" : { "term" : { "tenant_id" : "5242-TENANTID-ef615" } }` to whatever other query/filters are included in the `_search` query

**Comment by dpb587** [comment]
I didn't realize filtered aliases were coming to elasticsearch. That will be very useful.

For filtered aliases, I think the difficult part here would be ensuring the aliased indices always exist. Seems like there would need to be a secondary process to manage that.

For multiple indices, an implementation of #68 would be helpful.

**Comment by malston** [comment]
In the multi-tenant [PR](https://github.com/logsearch/logsearch-boshrelease/issues/74), I named this property "elasticsearch.index". Would you rather call it logstash_parser.index_format as was mentioned in #68?

**Comment by malston** [comment]
I could see us potentially supporting both ways with different QoS capabilities delivered by the service plan.  Perhaps, in the most basic plan, we can start by using filtered aliases to provide consumers with a mvp solution. Then we can scale up from there. 

I think in some environments, a Logsearch consumer would like to keep their tenant’s logs physically separated because I expect that they will have certain SLA requirements they’ll need to meet from tenant to tenant that could potentially only be met with separate physical infrastructure. But I don't think we want to solve that problem right now.

**Comment by simonjohansson** [comment]
I would love this feature.

Currently in our custom setup we have different logstash inputs for each CF env. 

```
$ cat cf_live_relp_input.conf 
input {  
  relp {
      type => relp
      port => 5141
      add_field => ["project", "cf", "env", "live"]
  }
}
```

And we then process logs from all our envs into a single ES cluster.

Would be great to have a logstash_ingestor.tennant property or similar.

**Comment by dpb587** [comment]
The following rough spec is from one of our recent discussions of supporting multiple ports. Reposting it here for documentation purposes, but it's not currently on our roadmap of things we're planning to work on ourselves. Happy to discuss this spec or (even better) PRs of it if anyone else needs this functionality enough to work on it themselves.

```
# inherit global logstash_ingestor.syslog_tls.* ssl settings, if configured
logstash_ingestor.syslog.multiport:
  # allow arbitrary, non-sequential ports
  - port: 5010
    # optionally add fields
    fields:
      app: "load-balancer"
    # optionally add tags
    tags:
      - "lowpri"
  - port: 5011
    # allow per-port ssl config
    ssl_cert: "{...file.contents...}"
    ssl_key: "{...file.contents...}"
  - port: 5021
    # when ssl is globally enabled, allow disabling it per-port
    ssl_cert: ~
```
