### ISSUE TITLE
How to use logsearch-filters-cf ?

### ISSUE THREAD

**Issue by shinji62** [logsearch/logsearch-boshrelease#82]
How can we inject logsearch-filters-cf ? I cannot find the actual documentation about filters.
Thanks

**Comment by dpb587** [comment]
Seems like we need to work on our documentation. In the meantime, it's probably easiest to get started with the following. We version our `filters.conf` file alongside our `deploy_manifest.yml` and embed it with BOSH's built-in ERB processing.
1. Download our default filters from [./jobs/log_parser/templates/config/filters_default.conf](https://github.com/logsearch/logsearch-boshrelease/blob/develop/jobs/log_parser/templates/config/filters_default.conf) to `filters.conf`
2. Download https://github.com/logsearch/logsearch-filters-cf, run `erb src/logstash/cloudfoundry.conf.erb` and append the result to `filters.conf`
3. Update your `deploy_manifest.yml` with the following:
   
   ```
   properties:
     logstash_parser:
       filters: |
               <%= File.read('filters.conf').gsub(/^/, '            ').strip %>
   ```
4. Deploy the latest changes with `bosh deploy`.
